### ISSUE TITLE
Unit Test on Angular Component 

### ISSUE THREAD

**Issue by Rajanusa** [ngneat/spectator#180]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The unit test of angular component fail.
Can you please help me.

## Minimal reproduction of the problem with instructions
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://bit.ly/2zme3bj).

**The angular component code.**
```
import { Component, OnInit } from '@angular/core';
import { FieldType } from '@ngx-formly/core';


@Component({
  selector: 'formly-field-tab',
  template: `
  <p-tabView (onChange)="handleChange($event)">
    <p-tabPanel *ngFor="let tab of field.fieldGroup;let index = index;" header="{{tab.key}}" [selected]="selectedTab==index">
      <ng-template pTemplate="content">
          <formly-field [field]="tab"></formly-field>
      </ng-template>
    </p-tabPanel>
  </p-tabView>
`,
})

export class FormlyFieldsTab extends FieldType {
  selectedTab: number = 0;
  public index: number;
  handleChange(event) {
    var index = event.index;
    this.activateTab(event.index);
  }
  activateTab(tabNumber) {
    this.selectedTab = tabNumber;
  }


}

```

**The Unit Test Code**

```

describe('FormlyFieldsTab', () => {
  let spectator: Spectator<FormlyFieldsTab>;
  const createComponent = createComponentFactory({
    declarations: [Component,FieldType],
    component: FormlyFieldsTab,
    imports: [],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
  });

  beforeEach(() => {
    spectator = createComponent();
  });
  it('should create', () => {
    expect(spectator.component).toBeTruthy();
  });

  it('activateTab', () => {
    spectator.component.activateTab(0);
    spectator.detectComponentChanges();
    expect(spectator.component.selectedTab).toBe(0);

  });

  it('handleChange', () => {
    spectator.component.handleChange({"index":1});
    spectator.detectComponentChanges();
    expect(spectator.component.selectedTab).toBe(1);

  });

});


```

**The following error is coming**

Failed: Unexpected value 'DecoratorFactory' declared by the module 'DynamicTestModule'. Please add a @Pipe/@Directive/@Component annotation.

```
error properties: Object({ ngSyntaxError: true })
Error: Unexpected value 'DecoratorFactory' declared by the module 'DynamicTestModule'. Please add a @Pipe/@Directive/@Component annotation.
    at syntaxError (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/compiler/fesm2015/compiler.js:2175:1)
    at http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/compiler/fesm2015/compiler.js:19710:1
    at <Jasmine>
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/compiler/fesm2015/compiler.js:19692:1)
    at JitCompiler._loadModules (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/compiler/fesm2015/compiler.js:25402:1)
    at JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/compiler/fesm2015/compiler.js:25391:1)
    at JitCompiler.compileModuleAndAllComponentsAsync (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/compiler/fesm2015/compiler.js:25353:1)
    at CompilerImpl.compileModuleAndAllComponentsAsync (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/platform-browser-dynamic/fesm2015/platform-browser-dynamic.js:237:1)
    at TestingCompilerImpl.compileModuleAndAllComponentsAsync (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/platform-browser-dynamic/fesm2015/testing.js:140:1)
    at TestBedViewEngine.compileComponents (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/testing.js:3086:1)

```
## What is the motivation / use case for changing the behavior?

I think,  createComponentFactory() is not called with proper parameter.
Please help me

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
`declarations: [Component,FieldType]` <===== `FieldType`?

Next time, please add a live demo. Thanks.

**Comment by Rajanusa** [comment]
Hi,

I removed component and field type from declaration but still getting error.
Please help me.
I am not sure how to create angular library with test case in stack blitz. 
It create angular project but not the library. 

**1. FormlyFieldsTab > handleChange
TypeError: Cannot read property 'fieldGroup' of undefined**

**2. TypeError: Cannot read property 'component' of undefined**

3. FormlyFieldsTab > should create
TypeError: Cannot read property 'fieldGroup' of undefined

4. FormlyFieldsTab > activateTab
TypeError: Cannot read property 'fieldGroup' of undefined
```
error properties: Object({ ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 17055745, rootNodeFlags: 1, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 1, childFlags: 17055745, directChildFlags: 16777217, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 2, bindings: [  ], bindingFlags: 0, outputs: [ Object({ type: 0, target: null, eventName: 'onChange', propName: null }) ], element: Object({ ns: '', name: 'p-tabView', attrs: [  ], template: null, componentProvider: null, componentView: null, componentRendererType: null, publicProviders: null({  }), allProviders: null({  }), handleEvent: Function }), provider: null, text: null, query: null, ngContent: null }), Object({ nodeIndex: 1, parent: Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex ...
    at <Jasmine>
    at Object.eval [as updateDirectives] (ng:///DynamicTestModule/FormlyFieldsTab.ngfactory.js:38:31)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:36055:1)
    at checkAndUpdateView (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35067:1)
    at callViewAction (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35433:1)
    at execComponentViewsAction (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35361:1)
    at checkAndUpdateView (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35074:1)
    at callWithDebugContext (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:36407:1)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:35990:1)
    at ViewRef_.detectChanges (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/core.js:23807:1)
    at ComponentFixture._tick (http://localhost:9876/_karma_webpack_/webpack:/C:/GitLab/Thanos/synapse.ui.component/node_modules/@angular/core/fesm2015/testing.js:317:1)
```
I get CORS Policy issue in console.
zone-evergreen.js:2981 Access to XMLHttpRequest at 'ng:///DynamicTestModule/ObjectTypeComponent.ngfactory.js' from origin 'http://localhost:9876' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by benelliott** [comment]
@Rajanusa This is an error in your application and is not related to Spectator. You have created a lot of issues in the last few days and they have all been errors in your own code. Please can you try a bit harder yourself before asking for support, and then consider other forums for it when you do, such as Reddit, Gitter or StackOverflow.

GitHub issues are intended to be used when you find an issue with the library code itself.
