### ISSUE TITLE
Ivy Support

### ISSUE THREAD

**Issue by unlight** [ngneat/spectator#186]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Trying to use [first example](https://github.com/ngneat/spectator#testing-components) of testing components and got error.

```
      Error: Unexpected value 'EntryComponentModule' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.
            at verifySemanticsOfNgModuleDef (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:37280:1)
            at http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:37298:1
            at <Jasmine>
            at verifySemanticsOfNgModuleDef (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:37292:1)
            at Function.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:37244:1)
            at R3TestBedCompiler.applyProviderOverridesToModule (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:2028:44)
            at R3TestBedCompiler.compileTestModule (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:2300:1)
            at R3TestBedCompiler.finalize (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:1841:1)
            at TestBedRender3.get testModuleRef [as testModuleRef] (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:3162:1)
            at TestBedRender3.inject (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:3024:1)
        TypeError: Cannot read property 'component' of undefined
            at <Jasmine>
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/+feature/feature.component.spec.ts:12:54)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:365:1)
            at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:305:1)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
            at Zone.run (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:124:1)
            at runInTestZone (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:554:1)
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:569:1)
```

## Expected behavior
No errors

## Minimal reproduction of the problem with instructions
```
describe('FeatureComponent', () => {
    let spectator: Spectator<FeatureComponent>;
    const createComponent = createComponentFactory(FeatureComponent);

    beforeEach(() => (spectator = createComponent()));

    it('should ...', () => {
    });
});
```

## Environment

<pre><code>
@angular/* 9.0.0-next.5
"@ngneat/spectator": "4.2.1"

Browser:
- [x] Chrome (desktop) version 76
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.9.1
- Platform:  Windows

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
You are using Ivy. We didn't test the library with Ivy yet.

**Comment by NetanelBasal** [comment]
We'll check it soon, and update the issue. Thanks for the report.

**Comment by unlight** [comment]
I'm not sure is it really needed ivy support in unit tests.
So, I found that ivy can be disabled for unit tests `tsconfig.spec.json`
```json
  "angularCompilerOptions": {
    "enableIvy": false,
  }
```
https://angular.io/guide/ivy

**Comment by NetanelBasal** [comment]
And it worked?

**Comment by NetanelBasal** [comment]
Could you try v4.2.2, please? I added a fix.

**Comment by unlight** [comment]
> And it worked?
Yes, it works.

And version 4.2.2 also works with `"enableIvy": true`

**Comment by NetanelBasal** [comment]
Great.
