### ISSUE TITLE
TypeError: Cannot read property 'getComponentFromError' of null and TypeError: testing.TestBed.inject is not a function

### ISSUE THREAD

**Issue by imnickvaughn** [ngneat/spectator#286]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x ] Documentation issue or request
[ x ] Support request
[ ] Other... Please describe:
</code></pre>

ALL FILES ZIPPED BELOW

## Current behavior

Hello, I am trying to follow your documentation regarding [testing with http](https://github.com/ngneat/spectator/blob/master/README.md#testing-with-http), but I am having trouble getting the http test to pass.

I have been reading countless articles and checking examples trying to fix this for a few days but have been unsuccessful.  Any ideas?
![image](https://user-images.githubusercontent.com/24948723/75817759-b94af980-5d65-11ea-86c5-f2851797fe29.png)
```
PASS projects/geode-lib/src/lib/geode-security-lookup/geode-security-lookup.component.spec.ts
 FAIL  projects/geode-lib/src/lib/geode-security-lookup/geode-security-lookup.service.spec.ts
  ● HttpClient testing › can test HttpClient.get

    TypeError: Cannot read property 'getComponentFromError' of null

      at TestBedViewEngine._initIfNeeded (../../packages/core/testing/src/test_bed.ts:378:46)
      at TestBedViewEngine.get (../../packages/core/testing/src/test_bed.ts:464:10)
      at Function.TestBedViewEngine.get (../../packages/core/testing/src/test_bed.ts:228:36)
      at node_modules/@ngneat/spectator/bundles/ng:/@ngneat/spectator/lib/spectator-http/create-factory.ts:50:41
      at Object.beforeEach (projects/geode-lib/src/lib/geode-security-lookup/geode-security-lookup.service.spec.ts:24:32)

  ● HttpClient testing › can test HttpClient.get

    TypeError: Cannot read property 'service' of undefined

      25 | 
      26 |   it('can test HttpClient.get', () => {
    > 27 |     spectator.service.getAutoCompleteData("1", "http://localhost:8050/locator", "/ws/search/securityLookup").subscribe();
         |               ^
      28 |     spectator.expectOne('http://localhost:8050/locator/ws/search/securityLookup?filter[searchTerm]=1', HttpMethod.GET);
      29 |   });
      30 | });

      at Object.it (projects/geode-lib/src/lib/geode-security-lookup/geode-security-lookup.service.spec.ts:27:15)

  ● HttpClient testing › can test HttpClient.get

    TypeError: testing.TestBed.inject is not a function

      at Object.<anonymous> (node_modules/@ngneat/spectator/bundles/ng:/@ngneat/spectator/lib/spectator-http/create-factory.ts:37:13)

------------------------------------|----------|----------|----------|----------|-------------------|
File                                |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------------------------|----------|----------|----------|----------|-------------------|
All files                           |    48.98 |        0 |    14.29 |    40.48 |                   |
 geode-security-lookup.component.ts |    67.86 |        0 |       25 |    60.87 |... 59,62,83,84,89 |
 geode-security-lookup.service.ts   |    23.81 |        0 |        0 |    15.79 |... 56,57,58,61,64 |
------------------------------------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        7.238s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.
```

## Expected behavior

If I follow the tutorial, I could easily test a function using the injected httpClient.

## Minimal reproduction of the problem with instructions
To reproduce:
1. $npm i
2. $ jest --coverage --onlyChanged --watch --colors

All files zipped here:
[angular.zip](https://github.com/ngneat/spectator/files/4283523/angular.zip)

here are the relevant files:
ng-component-lib\projects\geode-lib\src\lib\geode-security-lookup\geode-security-lookup.service.spec.ts
```
import { createHttpFactory, HttpMethod, SpectatorHttp } from '@ngneat/spectator';
import { GeodeSecurityLookupService } from "./geode-security-lookup.service";

// describe("GeodeSecurityLookupService", () => {
//   it("#getMockAutoCompleteData should only return data that matches string", () => {
//     const service = new GeodeSecurityLookupService(null);
//     const expect1 = [{
//       edmSecId: "1",
//       idCusip: "CUSIP1",
//       idSedol: "SEDOL1",
//       idTicker: "TICKER1",
//       securityName: "Security Name 1"
//     }]
//     expect(service.getMockAutoCompleteData("1")).toStrictEqual(expect1);
//   });


// })

describe("HttpClient testing", () => {
  let spectator: SpectatorHttp<GeodeSecurityLookupService>;
  const createHttp = createHttpFactory(GeodeSecurityLookupService);

  beforeEach(() => spectator = createHttp());

  it('can test HttpClient.get', () => {
    spectator.service.getAutoCompleteData("1", "http://localhost:8050/locator", "/ws/search/securityLookup").subscribe();
    spectator.expectOne('http://localhost:8050/locator/ws/search/securityLookup?filter[searchTerm]=1', HttpMethod.GET);
  });
});
```

ng-component-lib\projects\geode-lib\src\lib\geode-security-lookup\geode-security-lookup.service.ts
```
import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from "@angular/common/http";

@Injectable({
  providedIn: 'root'
})
export class GeodeSecurityLookupService {


  constructor(private http: HttpClient) { }

  public getAutoCompleteData(
    searchTerm: string,
    baseUrl: string,
    endpointUrl: string,
  ) {
    let params: HttpParams = new HttpParams();
    if (searchTerm !== null) {
      params = params.set("filter[searchTerm]", searchTerm);
    }
    return this.http
      .get(baseUrl + endpointUrl, {
        params: params
      })
  }

  public getMockAutoCompleteData(searchTerm: string): Array<any> {
    const mockData = [
      {
        edmSecId: "1",
        idCusip: "CUSIP1",
        idSedol: "SEDOL1",
        idTicker: "TICKER1",
        securityName: "Security Name 1"
      },
      {
        edmSecId: "2",
        idCusip: "CUSIP2",
        idSedol: "SEDOL2",
        idTicker: "TICKER2",
        securityName: "Security Name 2"
      }
    ]
    // return mockData;
    return this.filterObject(searchTerm, mockData);
  }

  // if string is found in any value of an object within the array, the object is included in the array for the dropdown
  private filterObject(searchTerm, arrObjs) {
    const result = arrObjs.filter(obj => {
      let valueFound = false
      Object.entries(obj).some(
        ([key, value]) => {
          const found = (value as string).toUpperCase().search(searchTerm.toUpperCase())

          if (found !== -1) {
            valueFound = true
            return
          }
        })
      return valueFound;
    }
    );
    return result
  }
}
```

ng-component-lib\projects\geode-lib\src\lib\geode-security-lookup\geode-security-lookup.component.ts
```
import { Component, OnInit, Output, EventEmitter, Input } from "@angular/core";
import { GeodeSecurityLookupService } from "./geode-security-lookup.service";
import CustomStore from "devextreme/data/custom_store";
import notify from "devextreme/ui/notify";

@Component({
  selector: "lib-geode-security-lookup",
  templateUrl: "./geode-security-lookup.component.html",
  styleUrls: ["./geode-security-lookup.component.scss"]
})
export class GeodeSecurityLookupComponent implements OnInit {

  // emitted after a click or enter event
  @Output() dropdownItemSelectedEvent: EventEmitter<string> = new EventEmitter<string>();

  // baseUrl and endpointUrl will be joined together and called when a user enters text into the lookup field
  // e.g. http://localhost:8050/locator/ws/search/securityLookup?filter%5BsearchTerm%5D=
  //
  // endpoint URL MUST be a GET endpoint that accepts a param called "filter[searchTerm]" and must return an array of objects with the key/value pairs
  //   edmSecId: number
  //   idCusip: string
  //   idSedol: string
  //   idTicker: string
  //   securityName: string
  @Input() baseUrl: string; // e.g. http://localhost:8050/locator
  @Input() endpointUrl: string; // e.g. /ws/search/securityLookup?filter%5BsearchTerm%5D=

  // since modern applications will have http Interceptors to append auth headers, this should be used to test and should be used for applications without interceptors
  @Input() token: string;

  // inital input value
  @Input() value: string = "";

  // Use mock data rather than baseURL + endpointURL?
  @Input() testMode: boolean = false;

  // Data source for storing lookup results
  dataSource: any = {};

  constructor(private searchService: GeodeSecurityLookupService) { }

  ngOnInit() {
    // building the DevExtreme store

    this.dataSource.store = new CustomStore({
      key: "edmSecId",
      load: ():
        Promise<any> | Array<any> => {
        if (this.testMode) {
          return this.searchService.getMockAutoCompleteData(this.value);
        } else {
          return this.searchService.getAutoCompleteData(
            this.value,
            this.baseUrl,
            this.endpointUrl,
          )
            .toPromise()
            .then((data: any) => {
              return data;
            })
            .catch(error => {
              notify(
                "Error loading Security Lookup data: " + error.error,
                "error",
                30000
              );
            });
        }
      }
    });
  }

  // the input search string, "searchTerm", is being updated independently
  updateSearchTermValue(value) {
    this.value = value;
  }

  // this is where we the select the value in the dropdown
  // right now all we are doing is emitting it to the parent
  // click is used to select an option, we can simply emit that
  // if enter is used to select an option, we need to use the value to filter, get the right object, and then emit that
  public updateRow(item) {
    if (typeof item === "object") {
      this.sendSelectedDropdownItem(item)
    }
  }

  private sendSelectedDropdownItem(item) {
    this.dropdownItemSelectedEvent.emit(item)
  }

}
```

## What is the motivation/use case for changing the behavior?
I am hoping to use your library to make testing more manageable for my team and I.

## Environment
     "@angular/common": "^8.2.13",
        "@angular/core": "^8.2.13",
        "devextreme": "^19.2.3",
        "devextreme-angular": "^19.2.3"

 
For Tooling issues:
node version v10.16.3
Windows 10

**Comment by imnickvaughn** [comment]
Having the same issue making tests in the other file too.


```
PASS  projects/geode-lib/src/lib/geode-security-lookup/geode-security-lookup.service.spec.ts
 FAIL  projects/geode-lib/src/lib/geode-security-lookup/geode-security-lookup.component.spec.ts
  ● GeodeSecurityLookupComponent › #updateRow should emit a dropdownItemSelectedEvent

    TypeError: Cannot read property 'getComponentFromError' of null

      at TestBedViewEngine._initIfNeeded (../../packages/core/testing/src/test_bed.ts:378:46)
      at TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:570:10)
      at Function.TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:232:36)
      at Object.it (projects/geode-lib/src/lib/geode-security-lookup/geode-security-lookup.component.spec.ts:15:29)

------------------------------------|----------|----------|----------|----------|-------------------|
File                                |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------------------------|----------|----------|----------|----------|-------------------|
All files                           |    73.47 |       25 |       50 |    69.05 |                   |
 geode-security-lookup.component.ts |    67.86 |        0 |       25 |    60.87 |... 59,62,83,84,89 |
 geode-security-lookup.service.ts   |    80.95 |       50 |    83.33 |    78.95 |       17,18,19,21 |
------------------------------------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        6.809s, estimated 7s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.
```


ng-component-lib\projects\geode-lib\src\lib\geode-security-lookup\geode-security-lookup.component.spec.ts
````
import { GeodeSecurityLookupComponent } from "./geode-security-lookup.component";
import { TestBed } from "@angular/core/testing";
import { By } from "@angular/platform-browser";
import { Spectator, createComponentFactory } from "@ngneat/spectator";

describe("GeodeSecurityLookupComponent", () => {
  // it("#updateSearchTerm should set this.value", () => {
  //   const component = new GeodeSecurityLookupComponent(null);
  //   const value = "1";
  //   component.updateSearchTermValue(value);
  //   expect(component.value).toBe(value);
  // });


  it("#updateRow should emit a dropdownItemSelectedEvent", () => {
    const fixture = TestBed.createComponent(GeodeSecurityLookupComponent)
    const component = new GeodeSecurityLookupComponent(null);

    let spectator: Spectator<GeodeSecurityLookupComponent>;
    const createComponent = createComponentFactory(GeodeSecurityLookupComponent);
    beforeEach(() => spectator = createComponent());

    let event = "";
    const expect1 = [{
      edmSecId: "1",
      idCusip: "CUSIP1",
      idSedol: "SEDOL1",
      idTicker: "TICKER1",
      securityName: "Security Name 1"
    }]

    this.fixture.whenStable().then(
      () => {
        fixture.detectChanges();
        const inputEl = fixture.debugElement.query(By.css(".geode--search-cursor-icon-space"));
        inputEl.nativeElement.value = 1
        inputEl.nativeElement.focus();


        spectator.keyboard.pressKey("1");
        component.dropdownItemSelectedEvent.subscribe(value => event = value)
        fixture.detectChanges();
      }
    );
    expect(event).toStrictEqual(expect1);
  })
});
```

**Comment by NetanelBasal** [comment]
Can you specify the Angular and Spectator versions?

**Comment by imnickvaughn** [comment]
Yep,

      "@angular/compiler": "~8.2.13",
        "@angular/core": "~8.2.13",

        "@ngneat/spectator": "^5.2.1",

**Comment by NetanelBasal** [comment]
You need to use v4+.
