### ISSUE TITLE
Support jest-circus

### ISSUE THREAD

**Issue by RobinVdBroeck** [ngneat/spectator#314]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently spectator does not work with jest-circus.
Stacktrace:
```
 ReferenceError: jasmine is not defined

      at ../../node_modules/@ngneat/spectator/bundles/ng:/@ngneat/spectator/lib/spectator/create-factory.ts:70:5
      at ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:386:30)
      at AsyncTestZoneSpec.onInvoke (../../node_modules/zone.js/dist/async-test.js:102:47)
      at ProxyZoneSpec.onInvoke (../../node_modules/zone.js/dist/proxy.js:114:43)
      at ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:385:36)
      at Zone.runGuarded (../../node_modules/zone.js/dist/zone.js:154:51)
      at runInTestZone (../../node_modules/zone.js/dist/async-test.js:224:33)
      at ../../node_modules/zone.js/dist/async-test.js:179:21
      at new ZoneAwarePromise (../../node_modules/zone.js/dist/zone.js:913:33)
      at ../../node_modules/zone.js/dist/async-test.js:178:24
      at ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.onInvoke (../../node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:385:36)
      at Zone.run (../../node_modules/zone.js/dist/zone.js:143:47)
```
## Expected behavior
Spectator supports jest-circus

## Minimal reproduction of the problem with instructions
Any test that uses spectator/jest will throw following error: `ReferenceError: jasmine is not defined`

## What is the motivation / use case for changing the behavior?
Jest-jasmine wil not be bundled in Jest 28 ([Source](https://jestjs.io/blog/2020/05/05/jest-26))

## Environment

<pre><code>
Angular version: 9.1.7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.17.0 
- Platform: Linux, Windows (not tested on Mac) 

Others:

- Jest version: 26.0.1
- Jest preset angular: 8.2.0
</code></pre>

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR.
