### ISSUE TITLE
Simple test of a component with no dependencies (with angular's default configuration and Jasmine) errors with Cannot configure the test module when the test module has already been instantiated. Make sure you are not using `inject` before `R3TestBed.configureTestingModule`.

### ISSUE THREAD

**Issue by joshiraez** [ngneat/spectator#335]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Given the following component:

```html
<div class="container">
    <span class="name">{{ this.character.name }}</span>
    <span class="height">{{ this.character.height }} cm</span>
    <span class="mass">{{ this.character.mass }} kg</span>
    <span class="birthday">{{ this.character.birth_year }}</span>
    <span class="hairColor">{{ this.character.hair_color }}</span>
    <span class="skinColor">{{ this.character.skin_color }}</span>
    <span class="gender">{{ this.character.gender }}</span>
</div>
```
```typescript
import { Component, Input } from '@angular/core';
import StarWarsCharacter from '../../types/star-wars-character';

@Component({
  selector: 'app-star-wars-character-profile',
  templateUrl: './star-wars-character-profile.component.html',
  styleUrls: ['./star-wars-character-profile.component.scss']
})
export class StarWarsCharacterProfileComponent {

  @Input() character: StarWarsCharacter;
}
```

I use the following test for a sanity check and see the configuration is alright:
```typescript
import { createComponentFactory, Spectator } from '@ngneat/spectator';
import { StarWarsCharacterProfileComponent } from './star-wars-character-profile.component';
import StarWarsCharacter from '../../types/star-wars-character';

const LUKE : StarWarsCharacter = 
  {
    name: "Wedge Antilles",
    height: 170,
    mass: 77,
    hair_color: "brown",
    skin_color: "fair",
    birth_year: "21BBY",
    gender: "male",
  }

fdescribe('StarWarsCharacterProfileComponent', () => {

  const createComponent = createComponentFactory(StarWarsCharacterProfileComponent);
  let spectator : Spectator<StarWarsCharacterProfileComponent>;

  beforeEach( () => spectator = createComponent());

  it('should create', () => {
    //Given
    spectator.setInput('character', LUKE);

    //When

    //Then
    expect(spectator).toBeTruthy();
  });
});
```

Which, according to the docs, I'm copying down to the beforeEach structure.

Yet, the test fails with this error:
```
Chrome 80.0.3987 (Linux 0.0.0) StarWarsCharacterProfileComponent should create FAILED
        Failed: Cannot configure the test module when the test module has already been instantiated. Make sure you are not using `inject` before `R3TestBed.configureTestingModule`.
        Error: Cannot configure the test module when the test module has already been instantiated. Make sure you are not using `inject` before `R3TestBed.configureTestingModule`.
            at TestBedRender3.assertNotInstantiated (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:3265:1)
            at TestBedRender3.configureTestingModule (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:3089:1)
            at Function.configureTestingModule (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:2910:1)
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/node_modules/@ngneat/spectator/__ivy_ngcc__/fesm2015/ngneat-spectator.js:1355:16)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
            at AsyncTestZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:1032:1)
            at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:289:1)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:363:1)
            at Zone.runGuarded (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:133:1)
            at runInTestZone (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:1154:1)
        TypeError: Cannot read property 'name' of undefined
            at <Jasmine>
            at StarWarsCharacterProfileComponent_Template (ng:///StarWarsCharacterProfileComponent.js:36:47)
            at executeTemplate (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11949:1)
            at refreshView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11796:1)
            at refreshComponent (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:13229:1)
            at refreshChildComponents (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11527:1)
            at refreshView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11848:1)
            at renderComponentOrTemplate (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11922:1)
            at tickRootContext (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:13391:1)
            at detectChangesInRootView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:13425:1)
            at RootViewRef.detectChanges (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:15103:22)
        TypeError: Cannot read property 'setInput' of undefined
            at <Jasmine>
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/exercise/exercise/components/star-wars-character-profile/star-wars-character-profile.component.spec.ts:25:15)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
            at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:292:1)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:363:1)
            at Zone.run (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:123:1)
            at runInTestZone (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:545:1)
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:560:1)
            at <Jasmine>
Chrome 80.0.3987 (Linux 0.0.0): Executed 1 of 32 (1 FAILED) (0 secs / 0.145 secs)
Chrome 80.0.3987 (Linux 0.0.0) StarWarsCharacterProfileComponent should create FAILED
        Failed: Cannot configure the test module when the test module has already been instantiated. Make sure you are not using `inject` before `R3TestBed.configureTestingModule`.
        Error: Cannot configure the test module when the test module has already been instantiated. Make sure you are not using `inject` before `R3TestBed.configureTestingModule`.
            at TestBedRender3.assertNotInstantiated (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:3265:1)
            at TestBedRender3.configureTestingModule (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:3089:1)
            at Function.configureTestingModule (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:2910:1)
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/node_modules/@ngneat/spectator/__ivy_ngcc__/fesm2015/ngneat-spectator.js:1355:16)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
            at AsyncTestZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:1032:1)
            at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:289:1)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:363:1)
            at Zone.runGuarded (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:133:1)
            at runInTestZone (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:1154:1)
        TypeError: Cannot read property 'name' of undefined
            at <Jasmine>
            at StarWarsCharacterProfileComponent_Template (ng:///StarWarsCharacterProfileComponent.js:36:47)
            at executeTemplate (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11949:1)
            at refreshView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11796:1)
            at refreshComponent (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:13229:1)
            at refreshChildComponents (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11527:1)
            at refreshView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11848:1)
            at renderComponentOrTemplate (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11922:1)
            at tickRootContext (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:13391:1)
            at detectChangesInRootView (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:13425:1)
            at RootViewRef.detectChanges (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:15103:22)
        TypeError: Cannot read property 'setInput' of undefined
            at <Jasmine>
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/exercise/exercise/components/star-wars-character-profile/star-wars-character-profile.component.spec.ts:25:15)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
            at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:292:1)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:363:1)
            at Zone.run (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:123:1)
            at runInTestZone (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:545:1)
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:560:1)
Chrome 80.0.3987 (Linux 0.0.0): Executed 1 of 32 (1 FAILED) (skipped 31) ERROR (0.227 secs / 0.145 secs)
```

## Expected behavior
The test should pass

## Minimal reproduction of the problem with instructions
* Create a new app with Angular CLI
* Create a new component (I guess the name doesn't matter)
* Paste the code
* Run the test
(I'll be editing the issue shortly with a link to the demo, to see if it's maybe my configuration, I dont know)

## Environment

<pre><code>
Angular version: 9.0.7
Spectator: ^5.13.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by benelliott** [comment]
@joshiraez Did you make that demo?

**Comment by joshiraez** [comment]
Will try to do one after work, i'm sorry. Yesterday it got pretty late and seeing I have to write all the files by hand in the page I wanted to get some sleep before.

Also I was hoping to see if someone had a issue similar to this, because I heavily suspect it has more to do with installation, spectator version is wrong, tsconfig, dunno-something-like-that than to the code itself, but I dont know where to look :(

Anyway, demo later, and we can see after that wat comes to light

**Comment by joshiraez** [comment]
https://ng-run.com/edit/EuiUTwPvjCBDKQ8Du8sL?open=src%2Ftest.ts&test=true

Tried doing a demo but I'm having problems running the tests on the given platform (first, there were some packages that got stuck installing, and now I'm having strange errors on the proper angular configuration) and I'm not quite sure how the environment is set up.

You can see the code under test in the sw component. Ideally, the type of the input should be the StarWarsCharacter interface that is exported in the corresponding file, but I removed that because it seemed to also give problems.

I guess you could take a look and see what is missing in the configuration for it to work? I don't have this kind of errors at all in my environment...
