### ISSUE TITLE
Unexpected value 'NoopAnimationsModule' error in Angular 10.2.2

### ISSUE THREAD

**Issue by vinothpandian** [ngneat/spectator#363]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I wrote a simple test to check the component using `createComponentFactory` in Angular 10. It fails with the following error message

```bash
  TesterComponent
    × should create (426 ms)

  ● TesterComponent › should create

    Unexpected value 'NoopAnimationsModule' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.

      at verifySemanticsOfNgModuleDef (../packages/core/src/render3/jit/module.ts:180:13)
      at ../packages/core/src/render3/jit/module.ts:191:5
          at Array.forEach (<anonymous>)
      at verifySemanticsOfNgModuleDef (../packages/core/src/render3/jit/module.ts:189:58)
      at Function.get (../packages/core/src/render3/jit/module.ts:148:13)
      at R3TestBedCompiler.Object.<anonymous>.R3TestBedCompiler.applyProviderOverridesToModule (../packages/core/testing/src/r3_test_bed_compiler.ts:414:49)
      at R3TestBedCompiler.Object.<anonymous>.R3TestBedCompiler.compileTestModule (../packages/core/testing/src/r3_test_bed_compiler.ts:677:10)
      at R3TestBedCompiler.Object.<anonymous>.R3TestBedCompiler.finalize (../packages/core/testing/src/r3_test_bed_compiler.ts:245:10)
      at TestBedRender3.get (../packages/core/testing/src/r3_test_bed.ts:379:43)
      at TestBedRender3.Object.<anonymous>.TestBedRender3.inject (../packages/core/testing/src/r3_test_bed.ts:278:25)
      at TestBedRender3.Object.<anonymous>.TestBedRender3.createComponent (../packages/core/testing/src/r3_test_bed.ts:334:40)       
      at Function.Object.<anonymous>.TestBedRender3.createComponent (../packages/core/testing/src/r3_test_bed.ts:182:33)
      at createSpectator (node_modules/projects/spectator/src/lib/spectator/create-factory.ts:112:27)
      at node_modules/projects/spectator/src/lib/spectator/create-factory.ts:101:23
      at src/app/tester/tester.component.spec.ts:9:17
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:143:47)

  ● TesterComponent › should create

    TypeError: Cannot read property 'component' of undefined

      11 | 
      12 |   it('should create', () => {
    > 13 |     expect(spectator.component).toBeTruthy();
         |                      ^
      14 |   });
      15 | });
      16 | 

      at src/app/tester/tester.component.spec.ts:13:22
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:143:47
```

## Expected behavior
The test should not fail.

## Minimal reproduction of the problem with instructions
```typescript
// Code
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-tester',
  templateUrl: './tester.component.html',
  styleUrls: ['./tester.component.scss']
})
export class TesterComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

// Test case

import { createComponentFactory, Spectator } from '@ngneat/spectator';
import { TesterComponent } from './tester.component';

describe('TesterComponent', () => {
  let spectator: Spectator<TesterComponent>;
  const createComponent = createComponentFactory(TesterComponent);

  beforeEach(() => {
    spectator = createComponent();
  });

  it('should create', () => {
    expect(spectator.component).toBeTruthy();
  });
});
```

## What is the motivation / use case for changing the behavior?
To test a simple test case in the latest angular project

## Environment

<pre><code>
Angular version:10.2.2
@ngneat/spectator version:6.1.0
</code></pre>

**Comment by benelliott** [comment]
Please can you run `npm list @angular/core` in the root directory of your project?

**Comment by vinothpandian** [comment]
> Please can you run `npm list @angular/core` in the root directory of your project?

Here it is.

I am using `jest` by the way. I tried importing from jest sub dir as well (like below) but the same issue occurs
` import { createComponentFactory, Spectator } from '@ngneat/spectator/jest'; `

```sh
+-- UNMET PEER DEPENDENCY @angular/core@10.2.2
+-- @ngrx/schematics@10.0.1
| `-- @angular/core@10.1.6
`-- codelyzer@6.0.1
  `-- @angular/core@9.0.0

npm ERR! peer dep missing: @angular/core@>=7.0.0 <8.0.0, required by rete-angular-render-plugin@0.2.2
```

**Comment by vinothpandian** [comment]
Sorry for the false alarm. Figured that the postinstall `ngcc` did not run which led to this error.

If someone runs into the same issue, then you can find the explanations here: [https://angular.io/guide/ivy#ivy-and-universalapp-shell](https://angular.io/guide/ivy#ivy-and-universalapp-shell)
