### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by rogeriofonseca** [ngneat/spectator#411]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

when I run my test I received the following message: **"TypeError: Converting circular structure to JSON"**
I have a component with a dependency called **NewContractService**

**Spec file:**
```
describe('ProposalRegisterComponent', () => {
  let spectator: Spectator<ProposalRegisterComponent>;
  const createComponent = createComponentFactory<ProposalRegisterComponent>({
    component: ProposalRegisterComponent,
    imports: [PanelModule, ButtonModule, DialogModule],
    providers: [NewContractService],
    declareComponent: true
  });

  beforeEach(() => {
    spectator = createComponent();
  });

  it('should create', () => {
    expect(spectator.component).toExist();
  });
});
```

**Component File:**
```
import { Component, OnInit } from '@angular/core';
import { NewContractService } from '../new-contract.service';

@Component({
  selector: 'app-proposal-register',
  templateUrl: './proposal-register.component.html',
  styleUrls: ['./proposal-register.component.scss']
})
export class ProposalRegisterComponent implements OnInit {

  constructor(private newContractService: NewContractService) { }

  ngOnInit(): void {
  }

}
```

## Expected behavior

I expected that sentence **expect(spectator.component).toExist();** would be true.

## Environment

<pre><code>
Angular version: 10.2.0

For Tooling issues:
- Jest: 26.6.3 (dependency)
- Platform:  Mac (OSX) 

Others:

</code></pre>

## Complete error message
```
ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
ts-jest[root] (WARN) Import setup jest file via `import 'jest-preset-angular';` is deprecated and will be removed in v9.0.0. Please switch to `import 'jest-preset-angular/setup-jest';`
(node:53843) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:735:23)
    at process.target.send (internal/child_process.js:634:19)
    at reportSuccess (/Users/rogeriofonsecagoncalves/static-portal/node_modules/jest-runner/node_modules/jest-worker/build/workers/processChild.js:67:11)
(node:53843) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:53843) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

 RUNS  src/app/new-contract/proposal-register/proposal-register.component.spec.ts

Test Suites: 0 of 1 total
Tests:       0 total
Snapshots:   0 total
Time:        630 s
```

**Comment by rogeriofonseca** [comment]
I Solved my problem with **mockProvider(NewContractService)**

On **providers**
I replace that:
```
  const createComponent = createComponentFactory<ProposalRegisterComponent>({
    component: ProposalRegisterComponent,
    imports: [PanelModule, ButtonModule, DialogModule],

    providers: [NewContractService)],

    declareComponent: true,
    shallow: false
  });
```

For this:
```
  const createComponent = createComponentFactory<ProposalRegisterComponent>({
    component: ProposalRegisterComponent,
    imports: [PanelModule, ButtonModule, DialogModule],

    providers: [
      mockProvider(NewContractService)
    ],

    declareComponent: true,
    shallow: false
  });
```

**Comment by krzyhan** [comment]
you can also mock your service in `mocks:[NewContractService]` instead of in `providers:[mockProvider(NewContractService)]`

**Comment by krzyhan** [comment]
btw, if you have `Converting circular structure to JSON` error then you can run test again with `--runInBand` options to see more details (and it's better to run just one test in that case)
