### ISSUE TITLE
Overriding providers using factory function produces error

### ISSUE THREAD

**Issue by johngrimsey** [ngneat/spectator#455]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Overriding providers using the created factory function generates an error.

## Expected behavior
Providers should be overridden without error.

## Minimal reproduction of the problem with instructions
```Javascript
describe('MyComponent', () => {
  ...
 const createComponent = createComponentFactory({
    component: MyComponent,
    imports: [
       ModuleName
    ]
  });

  it('should override providers', () => {
    const spectator = createComponent({ providers: [MyProvider] });
  });
});
```

Is giving an error:

```bash
Cannot read property 'hasOwnProperty' of undefined
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at getOwnDefinition (/Users/xxx/Sites/packages/core/src/di/interface/defs.ts:197:15)
    at Object.getInjectableDef [as ɵgetInjectableDef] (/Users/xxx/Sites/packages/core/src/di/interface/defs.ts:189:10)
    at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine.overrideProviderImpl (/Users/xxx/Sites/packages/core/testing/src/test_bed.ts:572:45)
    at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine.overrideProvider (/Users/xxx/Sites/packages/core/testing/src/test_bed.ts:561:10)
    at Function.Object.<anonymous>.TestBedViewEngine.overrideProvider (/Users/xxx/Sites/packages/core/testing/src/test_bed.ts:226:29)
```
## Environment

Angular version: 12.1.1
Spectator version: 7.2.0

For Tooling issues:
- Node version: v14.15.4
- Platform:  Mac

**Comment by johngrimsey** [comment]
RTFM 🤦
