### ISSUE TITLE
`createServiceFactory` breaks with Angular 13 and Jest 7 with ESM modules

### ISSUE THREAD

**Issue by piotrl** [ngneat/spectator#516]
### Is this a regression?

Yes

### Description

Given Angular 13 went full ESM,  it seem that `createServiceFactory` causes an issue by loading ESM modules and `jest` seem to not understand that.

### Where it works?

other factories seem to work, e.g. `createComponentFactory` does not throw exception

### Minimal reproduction
```
import { createServiceFactory, SpectatorService } from '@ngneat/spectator/jest';
import { MyClass } from './my-class.service'; // empty class

describe('', () => {
  it('', () => {
    createServiceFactory(MyClass);
  });
});
```

### Please provide the exception or error you saw

```true
● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /node_modules/@ngneat/spectator/fesm2015/ngneat-spectator-jest.mjs:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { installProtoMethods, createComponentFactory as createComponentFactory$1, isType, Spectator as Spectator$1, createHttpFactory as createHttpFactory$1, SpectatorDirective as SpectatorDirective$1, createDirectiveFactory as createDirectiveFactory$1, createServiceFactory as createServiceFactory$1, SpectatorHost as SpectatorHost$1, createHostFactory as createHostFactory$1, SpectatorRouting as SpectatorRouting$1, createRoutingFactory as createRoutingFactory$1, SpectatorPipe as SpectatorPipe$1, createPipeFactory as createPipeFactory$1 } from '@ngneat/spectator';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module


    > 19 | import { createServiceFactory, SpectatorService } from '@ngneat/spectator/jest';
         | ^
      20 | import { GlobalFilterService } from './global-filter.service';
      21 |
      22 | describe('', () => {

      at Runtime.createScriptFromCode (../../../../node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/lib/topbar/global-filter/global-filter.service.spec.ts:19:1)

```

### Please provide the environment you discovered this bug in

```
* Angular 13.0.2
* `"@ngneat/spectator": "9.0.0",`
* `"jest": "27.2.3",`
* `"jest-preset-angular": "11.0.0",`
* `"ts-jest": "27.0.5",`
```

### Do you want to create a pull request?

No

**Comment by piotrl** [comment]
Likely it's on `jest` side to support it with workaround from https://jestjs.io/docs/ecmascript-modules
```
node --experimental-vm-modules node_modules/jest/bin/jest.js
```

I wanted to put this issue in google, now we can close it and likely it'll resolve itself as nrwl/nx changes default setup or node starts to understands ESM imports by default.
