### ISSUE TITLE
Ng13 - ng-packagr lib - Need to call TestBed.initTestEnvironment() first

### ISSUE THREAD

**Issue by JacobSiegle** [ngneat/spectator#546]
### Is this a regression?

Yes

### Description

All tests passed in Angular 12, updating to Angular 13 and Spectator 10.0.1 throws errors in any tests which touch components in a ng-packagr lib. Service / pipe tests still seem to work. All tests in other web apps (not ng-packagr libs) also work.

`Failed: Need to call TestBed.initTestEnvironment() first
        Error: Need to call TestBed.initTestEnvironment() first
            at TestBedRender3.get compiler [as compiler] (@angular/core/testing:1786:1)
            at TestBedRender3.configureTestingModule (@angular/core/testing:1709:1)
            at Function.TestBed [as configureTestingModule] (@angular/core/testing:1564:1)
            at UserContext.<anonymous> (node_modules/@ngneat/spectator/fesm2015/ngneat-spectator.mjs:1374:9)
            at _ZoneDelegate.invoke (projects/tei-shared/node_modules/zone.js/fesm2015/zone.js:372:1)
            at AsyncTestZoneSpec.onInvoke (projects/tei-shared/node_modules/zone.js/fesm2015/zone-testing.js:1200:1)
            at ProxyZoneSpec.onInvoke (projects/tei-shared/node_modules/zone.js/fesm2015/zone-testing.js:284:1)
            at _ZoneDelegate.invoke (projects/tei-shared/node_modules/zone.js/fesm2015/zone.js:371:1)
            at Zone.runGuarded (projects/tei-shared/node_modules/zone.js/fesm2015/zone.js:144:1)
            at runInTestZone (projects/tei-shared/node_modules/zone.js/fesm2015/zone-testing.js:1344:1)
        Error: Need to call TestBed.initTestEnvironment() first
            at TestBedRender3.get compiler [as compiler] (@angular/core/testing:1786:1)
            at TestBedRender3.get testModuleRef [as testModuleRef] (@angular/core/testing:1796:1)
            at TestBedRender3.inject (@angular/core/testing:1719:1)
            at TestBedRender3.createComponent (@angular/core/testing:1759:1)
            at Function.TestBed [as createComponent] (@angular/core/testing:1617:1)
            at createSpectator (node_modules/@ngneat/spectator/fesm2015/ngneat-spectator.mjs:1399:21)
            at node_modules/@ngneat/spectator/fesm2015/ngneat-spectator.mjs:1391:27
            at UserContext.<anonymous> (projects/tei-shared/src/lib/components/action-required-banner/action-required-banner.component.spec.ts:30:21)
            at _ZoneDelegate.invoke (projects/tei-shared/node_modules/zone.js/fesm2015/zone.js:372:1)
            at ProxyZoneSpec.onInvoke (projects/tei-shared/node_modules/zone.js/fesm2015/zone-testing.js:287:1)
        Error: <spyOn> : could not find an object to spy upon for getBanners$()
        Usage: spyOn(<object>, <methodName>)
        Error: <spyOn> : could not find an object to spy upon for getBanners$()
        Usage: spyOn(<object>, <methodName>)
            at <Jasmine>
            at UserContext.<anonymous> (projects/tei-shared/src/lib/components/action-required-banner/action-required-banner.component.spec.ts:35:30)
            at _ZoneDelegate.invoke (projects/tei-shared/node_modules/zone.js/fesm2015/zone.js:372:1)
            at ProxyZoneSpec.onInvoke (projects/tei-shared/node_modules/zone.js/fesm2015/zone-testing.js:287:1)
            at _ZoneDelegate.invoke (projects/tei-shared/node_modules/zone.js/fesm2015/zone.js:371:1)
            at Zone.run (projects/tei-shared/node_modules/zone.js/fesm2015/zone.js:134:1)
            at runInTestZone (projects/tei-shared/node_modules/zone.js/fesm2015/zone-testing.js:567:1)
            at UserContext.<anonymous> (projects/tei-shared/node_modules/zone.js/fesm2015/zone-testing.js:582:1)`

### Please provide the environment you discovered this bug in

```true
"engines": {
        "node": ">=16.14.2",
        "npm": ">=8.5.0"
    },

"@angular/core": "13.3.2",
```

### Do you want to create a pull request?

No

**Comment by JacobSiegle** [comment]
Managed to crack this one someone incorrectly added node_modules to my ng-packagr lib which will cause it to throw a bunch of unrelated errors like this.
