### ISSUE TITLE
mock.ts is missing import of jest

### ISSUE THREAD

**Issue by grosch** [ngneat/spectator#560]
### Is this a regression?

No

### Description

With newer jest versions you have to explicitly import jest.

### Please provide the exception or error you saw

```true
jest is not defined
ReferenceError: jest is not defined
    at /Users/scott/foo/lamp/node_modules/projects/spectator/jest/src/lib/mock.ts:15:20
    at installProtoMethods (/Users/scott/foo/lamp/node_modules/projects/spectator/src/lib/mock.ts:55:19)
    at createSpyObject (/Users/scott/foo/lamp/node_modules/projects/spectator/jest/src/lib/mock.ts:14:3)
    at Object.useFactory (/Users/scott/foo/lamp/node_modules/projects/spectator/jest/src/lib/mock.ts:44:23)
    at Object.factory (/Users/scott/packages/core/src/di/r3_injector.ts:417:32)
    at R3Injector.hydrate (/Users/scott/packages/core/src/di/r3_injector.ts:319:29)
    at R3Injector.get (/Users/scott/packages/core/src/di/r3_injector.ts:210:23)
    at R3Injector.get (/Users/scott/packages/core/src/di/r3_injector.ts:222:27)
    at ChainedInjector.get (/Users/scott/packages/core/src/render3/component_ref.ts:94:32)
    at lookupTokenUsingModuleInjector (/Users/scott/packages/core/src/render3/di.ts:368:31)
    at getOrCreateInjectable (/Users/scott/packages/core/src/render3/di.ts:417:10)
    at ɵɵdirectiveInject (/Users/scott/packages/core/src/render3/instructions/di.ts:52:10)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (ng:///AppComponent/ɵfac.js:5:78)
    at getNodeInjectable (/Users/scott/packages/core/src/render3/di.ts:625:38)
    at instantiateRootComponent (/Users/scott/packages/core/src/render3/instructions/shared.ts:1108:7)
    at createRootComponent (/Users/scott/packages/core/src/render3/component.ts:225:21)
    at ComponentFactory.create (/Users/scott/packages/core/src/render3/component_ref.ts:221:19)
    at initComponent (/Users/scott/packages/core/testing/src/r3_test_bed.ts:462:28)
    at l.invoke (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:13:6400)
    at ProxyZoneSpec.onInvoke (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:110:2047)
    at l.invoke (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:13:6340)
    at Object.onInvoke (/Users/scott/packages/core/src/zone/ng_zone.ts:406:29)
    at l.invoke (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:13:6340)
    at a.run (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:13:1812)
    at NgZone.run (/Users/scott/packages/core/src/zone/ng_zone.ts:185:50)
    at TestBedRender3.createComponent (/Users/scott/packages/core/testing/src/r3_test_bed.ts:465:37)
    at Function.createComponent (/Users/scott/packages/core/testing/src/r3_test_bed.ts:231:33)
    at createSpectator (/Users/scott/foo/lamp/node_modules/projects/spectator/src/lib/spectator/create-factory.ts:114:27)
    at /Users/scott/foo/lamp/node_modules/projects/spectator/src/lib/spectator/create-factory.ts:103:23
    at /Users/scott/foo/lamp/src/app/app.component.spec.ts:34:21
    at l.invoke (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:13:6400)
    at ProxyZoneSpec.onInvoke (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:110:2047)
    at l.invoke (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:13:6340)
    at a.run (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:13:1812)
    at Object.o (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:134:592)
    at Promise.then.completed (/Users/scott/foo/lamp/node_modules/jest-circus/build/utils.js:333:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/scott/foo/lamp/node_modules/jest-circus/build/utils.js:259:10)
    at _callCircusHook (/Users/scott/foo/lamp/node_modules/jest-circus/build/run.js:240:40)
    at _runTest (/Users/scott/foo/lamp/node_modules/jest-circus/build/run.js:202:5)
    at _runTestsForDescribeBlock (/Users/scott/foo/lamp/node_modules/jest-circus/build/run.js:97:9)
    at _runTestsForDescribeBlock (/Users/scott/foo/lamp/node_modules/jest-circus/build/run.js:91:9)
    at run (/Users/scott/foo/lamp/node_modules/jest-circus/build/run.js:31:3)
    at runAndTransformResultsToJestFormat (/Users/scott/foo/lamp/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
```

### Do you want to create a pull request?

Yes

**Comment by grosch** [comment]
Pull request at https://github.com/ngneat/spectator/pull/561

**Comment by NetanelBasal** [comment]
11.1.0
