### ISSUE TITLE
expect matchers are not extended with jest

### ISSUE THREAD

**Issue by grosch** [ngneat/spectator#562]
### Is this a regression?

Yes

### Description

The custom matchers you've defined, like toHaveExactText, do not work with jest setups.  

I'm 99% sure the issue is that there is no call to `expect.extend` as shown at [https://jestjs.io/docs/expect#expectextendmatchers](https://jestjs.io/docs/expect#expectextendmatchers) but I don't understand the setup enough to provide a PR for this fix.

### Please provide a link to a minimal reproduction of the bug

Just try to use one with a jest config and it'll fail.

### Please provide the exception or error you saw

```true
TypeError: expect(...).toHaveExactText is not a function
    at /Users/scott/foo/lamp/src/app/button-enabled-dialog/button-enabled-dialog.component.spec.ts:62:28
    at l.invoke (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:13:6400)
    at ProxyZoneSpec.onInvoke (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:110:2047)
    at l.invoke (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:13:6340)
    at a.run (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:13:1812)
    at Object.o (/Users/scott/foo/lamp/node_modules/zone.js/fesm2015/zone-testing-bundle.min.js:134:592)
    at Promise.then.completed (/Users/scott/foo/lamp/node_modules/jest-circus/build/utils.js:333:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/scott/foo/lamp/node_modules/jest-circus/build/utils.js:259:10)
    at _callCircusTest (/Users/scott/foo/lamp/node_modules/jest-circus/build/run.js:277:40)
    at _runTest (/Users/scott/foo/lamp/node_modules/jest-circus/build/run.js:209:3)
    at _runTestsForDescribeBlock (/Users/scott/foo/lamp/node_modules/jest-circus/build/run.js:97:9)
    at _runTestsForDescribeBlock (/Users/scott/foo/lamp/node_modules/jest-circus/build/run.js:91:9)
    at _runTestsForDescribeBlock (/Users/scott/foo/lamp/node_modules/jest-circus/build/run.js:91:9)
    at run (/Users/scott/foo/lamp/node_modules/jest-circus/build/run.js:31:3)
    at runAndTransformResultsToJestFormat (/Users/scott/foo/lamp/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 14.0.0
Node: 18.4.0 (Unsupported)
Package Manager: yarn 1.22.19 
OS: darwin arm64

Angular: 14.0.0
... animations, cdk, cli, common, core, forms, language-service
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0
@angular-devkit/build-angular   14.0.0
@angular-devkit/core            14.0.0
@angular-devkit/schematics      14.0.0
@angular/compiler               14.0.2
@angular/compiler-cli           14.0.2
@schematics/angular             14.0.0
ng-packagr                      14.0.0
rxjs                            6.6.3
typescript                      4.7.3
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Why does it still work here https://github.com/ngneat/spectator/blob/ac40000dfa6665468e24e22607351e90c3805501/projects/spectator/jest/test/hello/hello.component.spec.ts?

**Comment by grosch** [comment]
I'm going to *guess* that it's a difference between using ESM modules or not?

**Comment by grosch** [comment]
[example.zip](https://github.com/ngneat/spectator/files/8954905/example.zip)

Attached is a bare minimum project that is setup to use jest with ESM modules and shows the issue if you just do a 'yarn test'

**Comment by grosch** [comment]
@NetanelBasal Were you able to reproduce with the zip I provided?

**Comment by NetanelBasal** [comment]
Can you do it on stackblitz?

**Comment by grosch** [comment]
Maybe?  Not sure how that's easier than just using the zip I gave you.  I set it up at https://angular-ivy-rtojsi.stackblitz.io but I have no idea how to run jest on stackblitz so not sure if it'll fail the same way or not.

**Comment by NetanelBasal** [comment]
The issue is that `jest` is undefined [here](https://github.com/ngneat/spectator/blob/master/projects/spectator/src/lib/core.ts#L12).

**Comment by NetanelBasal** [comment]
v11.1.0

**Comment by grosch** [comment]
Thank you so much!
