### ISSUE TITLE
Issue with the update 11.1.1

### ISSUE THREAD

**Issue by ZeroGDrive** [ngneat/spectator#572]
### Is this a regression?

Yes

### Description

Now when trying to execute tests it will fail saying that require is not defined.

### Please provide the exception or error you saw

```true
Chrome 103.0.5060.134 (Mac OS 10.15.7) ERROR
  An error was thrown in afterAll
  Uncaught ReferenceError: require is not defined
  ReferenceError: require is not defined
      at Object.2404 (http://localhost:9877/_karma_webpack_/webpack:/node_modules/@ngneat/spectator/fesm2020/ngneat-spectator.mjs:746:11)
      at __webpack_require__ (http://localhost:9877/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.90 (http://localhost:9877/_karma_webpack_/main.js:13:75)
      at __webpack_require__ (http://localhost:9877/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at webpackContext (http://localhost:9877/_karma_webpack_/webpack:/src/ sync \.spec\.ts$:47:1)
      at Array.map (<anonymous>)
      at Object.4289 (http://localhost:9877/_karma_webpack_/webpack:/src/test.ts:26:16)
      at __webpack_require__ (http://localhost:9877/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9877/_karma_webpack_/main.js:4915:48)
      at http://localhost:9877/_karma_webpack_/main.js:4916:54
Chrome 103.0.5060.134 (Mac OS 10.15.7): Executed 0 of 0 ERROR (0 secs / 0 secs)
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
@arturovt

**Comment by arturovt** [comment]
I've created an issue in angular-cli.

**Comment by NetanelBasal** [comment]
The code is commented until we find a solution.
